### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by adbl**
Makes the iOS integration a bit easier and gives you control of the AppsFlyerFramework dependency version.

Changed a bit in the README to make the install procedure a bit clearer I hope, have a look and change if needed.

### CODE REVIEW

**Comment by adbl** [comment]
@af-fess please have a look at this when you have time 😊

**Comment by af-fess** [comment]
@adbl why do you want to put `react-native-appsflyer` into  `react-native-appsflyer.podspec`, its react-native plugin that should be installed through npm

**Comment by adbl** [comment]
Ooops `react-native-smooch` was a copy/paste error 😅 fixed.

The stuff from `package.json` into the podspec is just so the file is a valid podspec. It is not for publishing on CocoaPods. Having a separate podspec like this is common for RN bridges that depends on a native Pod, it makes the install simpler and safer.

**Comment by adbl** [comment]
@af-fess is there anything else I should explain regarding this PR?

**Comment by adbl** [comment]
@af-fess hello?

**Comment by af-fess** [comment]
@adbl hi, i need to test it first. Nee to find time for that. But it makes sense.

**Comment by adbl** [comment]
@af-fess ping, another month has gone by ...

**Comment by BenjaminAF** [comment]
@adbl In order for us to provide optimal support, we would kindly ask you to submit any issues to support@appsflyer.com
Please mention me by name (Benjamin) so I can take this on for you.

When submitting an issue please specify your AppsFlyer sign-up (account) email , your app ID , production steps, logs, code snippets and any additional relevant information.

**Comment by adbl** [comment]
Eh, ok I've sent an email @BenjaminAF

**Comment by adbl** [comment]
@af-fess while upgrading libraries for our project I notice this still hasn't been merged. I have now updated the PR to the current AppsFlyerFramework pod. If you don't want this documented then I can remove the README instructions? I just want this to get merged...

**Comment by Gyran** [comment]
This would really help!

**Comment by JesperLekland** [comment]
We need this! Please use a podspec for this library @af-fess

**Comment by adbl** [comment]
@af-fess can you please take 15 minutes to look at this and either merge it (or close it if you don't want to keep it)? I don't think ignoring a PR for many months is a nice way to treat a contributor and even less a paying customer.

cc @BenjaminAF 

Btw, here is a benefit to using this PR. In the README, it's stated that the RN bridge is built for AppsFlyer iOS SDK v4.7.11, however when installing according to the instructions, you end up with the currently latest version, (4.8.1 which I have put in the podspec and seem to work just fine btw). You want to lock the dependency version, which is possible with the podspec, you will update the podspec only when you have tested a new version. So, no users will come here and complain about some issue because they ended up with a new incompatible version, which may well happen otherwise.

**Comment by adbl** [comment]
Here are some other bridges which have a podspec:
https://github.com/davodesign84/react-native-mixpanel
https://github.com/smooch/react-native-smooch

**Comment by af-fess** [comment]
Hi @adbl , I didnt merge this pull because of small conflicts, I took your updates (etc) and generated this commit: https://github.com/AppsFlyerSDK/react-native-appsflyer/commit/f3a048ddd785ce2685c1355e28101b7199f9bb3e

**Comment by af-fess** [comment]
@adbl to be fair with you for your huge patience, I prefer to take your pull request and merge it instead my commit. Let me know if its makes sense :)

**Comment by adbl** [comment]
@af-fess excellent! I did rebase my branch on current master today, so there where no merge conflicts, but I can see you made some other changes to demo etc. This is fine 👍

**Pull request closed without merging**
