### PR TITLE
support typescript definition

### PR DESCRIPTION
**Pull request by Bang9**

### CODE REVIEW

**Comment by shaikou** [comment]
@wesfieldj Hello! Any plans on merging this in the near future? I see that PR is here from September and might be out of date already, so could you please let us know what is the blocker for merging TS definitions and if you need any additional help on this? Would be cool to have it merged. Thank you!

**Comment by wesfieldj** [comment]
@shaikou Looking into it now. Sorry for the delay.

**Comment by Bang9** [comment]
@wesfieldj Updated to the latest version !

**Comment by fabianlee1211** [comment]
Should have check if there is a PR already.
I made one on DefinitelyTyped, formatted and passed their test.
Perhaps we could merge our good stuff into one?
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42158

**Comment by Bang9** [comment]
> Should have check if there is a PR already. 🙍‍♂
> I made one on DefinitelyTyped, formatted and passed their test.
> Perhaps we could merge our good stuff into one?
> 
> Update: My PR has been merged. I suppose it would be available under ‘@ types’ soon.
> [DefinitelyTyped/DefinitelyTyped#42158](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42158)

@fabianlee1211
SHA256 not supported yet in iOS
I think you should fix the SHA256 in `EmailCryptType` enum
check #141

**Comment by fabianlee1211** [comment]
> > Should have check if there is a PR already. 🙍‍♂
> > I made one on DefinitelyTyped, formatted and passed their test.
> > Perhaps we could merge our good stuff into one?
> > Update: My PR has been merged. I suppose it would be available under ‘@ types’ soon.
> > [DefinitelyTyped/DefinitelyTyped#42158](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42158)
> 
> @fabianlee1211
> SHA256 not supported yet in react-native-appsflyer iOS
> I think you should fix the SHA256 in `EmailCryptType` enum
> check #141

Thanks mate! I guess I would keep it there because it wouldn't be a breaking problem. I believe your iOS PR will be merged soon!

**Pull request merged**
