### PR TITLE
Make project compatible with use_framework! option on Cocoapods

### PR DESCRIPTION
**Pull request by fjtrujy**
The project file was wrong built, it just contained 2 files, now I have added the missing files as well.

Thanks.

Note: Not sure if you need to publish a new `npm` version.

### CODE REVIEW

**Comment by jdgreenberger** [comment]
I can't build the project on iOS..but it looks like this will fix the issue. Can anyone review this?

**Comment by ArtisanalPickle** [comment]
Hope to see this merged too - same issue here

**Comment by fjtrujy** [comment]
Sorry I have updated the Master branch, I'm going to update also the PR.

Basically as you right now has the project is not compatible to be used in a `react-native` project that use `cocoapods` and `use_frameworks!` option.

Also I have improved how the imports are done and where the delegate protocol is declared.

Thanks

**Comment by af-fess** [comment]
@fjtrujy please check my latest update. 

I removed `s.dependency 'React'` from spec because its deprecated. Instead, clients will take it from npm a.e. 

```
pod 'React', :path => '../node_modules/react-native'
```


Without pods:

`RNAppsFlyer.xcodeproj` works with 2 files only: `RNAppsFlyer.h/m`. 

How do you load  AppsFlyer SDK, as `AppsFlyerLib.framework`  (static framework linking) or with Pods?


BYW this is a `demo` project configuration:

screen shot 2018-04-30 at 5 40 28 pm

**Pull request closed without merging**
